<?php

namespace App\Filament\Resources\OrderResource\Pages;

use App\Filament\Resources\OrderResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateOrder extends CreateRecord
{
    protected static string $resource = OrderResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        //dd($data);
        $data['caused_by'] = auth()->id();
        return $data; // TODO: Change the autogenerated stub
    }

    public function afterCreate()
    {
        //$data = [];
        /* $data['discount'] = collect($this->getRecord()->items)->sum(function ($item) {
            return $item->discount * $item->qty;
        }); */

        //$data['total'] = collect($this->getRecord()->items)->sum('sub_total');

        //$this->getRecord()->update($data);

        $this->getRecord()->orderLogs()->create([
            'log' => "Invoice created By: " . auth()->user()->name,
            'type' => 'created'
        ]);
    }
}
