<?php

namespace App\Filament\Resources\OrderResource\Pages;

use App\Filament\Resources\OrderResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditOrder extends EditRecord
{
    protected static string $resource = OrderResource::class;

    protected function mutateFormDataBeforeFill(array $data): array
    {
        // Determine if the order is for a guest or a registered customer
        $data['is_guest'] = is_null($data['customer_id']);
        return $data;
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        //dd($data);
        $data['caused_by'] = auth()->id();
        // If the order is for a registered customer...
        if ($data['is_guest'] === false) {
            // ...ensure the guest_customer field is null.
            $data['guest_customer'] = null;
        } else {
            // Otherwise, if it's a guest, ensure customer_id is null.
            $data['customer_id'] = null;
        }

        // Remove our virtual 'is_guest' field so Filament doesn't try to save it.
        unset($data['is_guest']);
        //dd($data);
        return $data; // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\ViewAction::make(),
            Actions\DeleteAction::make(),
        ];
    }
}
